name: free_dz
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.10.1


dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.1.1
  provider: ^6.0.5

 
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.7
  animated_notch_bottom_bar: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/splash.png

  android_12:
    image: assets/splash.png
    color: "#FFFFFF"

flutter:
  assets:
    - assets/images/logo.png

  
  uses-material-design: true

  
flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/logo.png"
  # DEFAULT is 16. To make it larger, use a smaller number.
  # Values between 0 and 5 will make the logo fill more of the safe zone.
  adaptive_icon_foreground_inset: 0
